### ISSUE TITLE
OS specific boolean envars

### ISSUE THREAD

**Issue by FelicianoTech** [CircleCI-Public/os-detect-orb#19]
Aside from just checking `$OSD_FAMILY` to see which OS type it is, I'd also like to be able to just check `$OSD_LINUX` or `$OSD_MACOS` for truthiness.

**Comment by dsayling** [comment]
@felicianotech is this something you'd still really like, or can we close this?

**Comment by KyleTryon** [comment]
Closing as wont-do. The team will be deprecating this orb
