### ISSUE TITLE
Add support for detecting Windows

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/os-detect-orb#3]
Currently supported operating systems:

| Executor/OS    | Supported? | Shell |
|---             |---         |---    |
| Docker/Ubuntu  | yes        | Bash  |
| Docker/Debian  | yes        | Bash  |
| Docker/Alpine  | yes        | Bash  |
| macOS          | yes        | Bash  |
| machine/Ubuntu | yes        | Bash  |

CircleCI has since announced support for Windows: https://circleci.com/build-environments/windows/.

Add the ability to detect and set env var data for Windows machines.

**Comment by distributedlock** [comment]
I'll take a crack at this.

**Comment by KyleTryon** [comment]
Marking as wont-do. There is still currently no easy way to take in data from detection and use that information to inform what shell in config to use. This will require platform changes.
